In [1]:
import re

import numpy as np
import torch
import torch.utils.data as data_utils

from lolip.models.torch_utils.archs import *
from lolip.variables import auto_var
from lolip.utils import estimate_local_lip, estimate_local_lip_v2
from params import mnistLip, cifarLip
from utils import params_to_dataframe

In [2]:
_, _, grid_params, _ = mnistLip()()
params_to_dataframe(grid_params, columns=['trn_acc', 'tst_acc', 'adv_trn_acc', 'adv_tst_acc', 'avg_trn_lip', 'avg_tst_lip', 'history'], result_file_dir='./results/experiment01/')

I1226 13:06:27.531631 139855695370048 auto_var.py:261] Running time: 0.002733
I1226 13:06:27.602882 139855695370048 auto_var.py:261] Running time: 0.002485
I1226 13:06:27.663352 139855695370048 auto_var.py:261] Running time: 0.002370
I1226 13:06:27.721719 139855695370048 auto_var.py:261] Running time: 0.002376
I1226 13:06:27.780065 139855695370048 auto_var.py:261] Running time: 0.002357
I1226 13:06:27.838659 139855695370048 auto_var.py:261] Running time: 0.002347
I1226 13:06:27.907860 139855695370048 auto_var.py:261] Running time: 0.002469
I1226 13:06:27.966541 139855695370048 auto_var.py:261] Running time: 0.002484
I1226 13:06:28.024966 139855695370048 auto_var.py:261] Running time: 0.002346
I1226 13:06:28.082932 139855695370048 auto_var.py:261] Running time: 0.002378


attack  dataset  eps                 model norm  random_seed   trn_acc  \
0    pgd    mnist  0.1         ce-tor-CNN001  inf            0  1.000000   
1    pgd    mnist  0.1  trades6ce-tor-CNN001  inf            0  0.999967   
2    pgd    mnist  0.1     curece-tor-CNN001  inf            0  1.000000   
3    pgd    mnist  0.1      advce-tor-CNN001  inf            0  0.999817   
4    pgd    mnist  0.1      llrce-tor-CNN001  inf            0  0.999983   
5    pgd  fashion  0.1         ce-tor-CNN001  inf            0  0.999533   
6    pgd  fashion  0.1  trades6ce-tor-CNN001  inf            0  0.976017   
7    pgd  fashion  0.1     curece-tor-CNN001  inf            0  1.000000   
8    pgd  fashion  0.1      advce-tor-CNN001  inf            0  0.888167   
9    pgd  fashion  0.1      llrce-tor-CNN001  inf            0  0.975550   

   tst_acc  adv_trn_acc  adv_tst_acc  avg_trn_lip  avg_tst_lip  \
0   0.9920     0.408133       0.4183    24.914808    25.083706   
1   0.9924     0.919833       0.9062     5.737867     5.748982   
2   0.9925     0.991367       0.9528     2.679286     2.685152   
3   0.9931     0.996400       0.9670     2.771575     2.795055   
4   0.9934     0.860450       0.8399    12.434842    12.424883   
5   0.9263     0.008750       0.0558    76.034775    76.180283   
6   0.9194     0.503983       0.5260     8.076009     8.072925   
7   0.9246     0.066433       0.1160    29.049671    28.866903   
8   0.8686     0.829900       0.8119     1.136331     1.133796   
9   0.9157     0.393817       0.4215     9.833105     9.933347   

                                             history  
0  [{'epoch': 1, 'trn_loss': 0.4666699381828308, ...  
1  [{'epoch': 1, 'trn_loss': 0.4758203192869822, ...  
2  [{'epoch': 1, 'trn_loss': 0.3844251032114029, ...  
3  [{'epoch': 1, 'trn_loss': 0.7555228825410207, ...  
4  [{'epoch': 1, 'trn_loss': 1.71617512169679, 't...  
5  [{'epoch': 1, 'trn_loss': 0.6656579953034719, ...  
6  [{'epoch': 1, 'trn_loss': 0.7347536305745442, ...  
7  [{'epoch': 1, 'trn_loss': 0.6249589390118917, ...  
8  [{'epoch': 1, 'trn_loss': 1.1296655715942383, ...  
9  [{'epoch': 1, 'trn_loss': 3.6845599964141846, ...

In [5]:
_, _, grid_params, _ = cifarLip()()
print(grid_params)
params_to_dataframe(grid_params, columns=['trn_acc', 'history'], result_file_dir='./results/experiment01/')

I1225 21:58:26.209870 140102087153472 auto_var.py:261] Running time: 0.000397
I1225 21:58:26.281889 140102087153472 auto_var.py:261] Running time: 0.000039
I1225 21:58:26.347605 140102087153472 auto_var.py:261] Running time: 0.000041


[{'dataset': ['cifar10'], 'model': ['ce-tor-WRN_40_10', 'tradesce-tor-WRN_40_10', 'trades6ce-tor-WRN_40_10', 'advce-tor-WRN_40_10', 'llrce-tor-WRN_40_10'], 'eps': [0.031], 'norm': ['inf'], 'attack': ['pgd'], 'random_seed': [0]}]


I1225 21:58:26.412562 140102087153472 auto_var.py:261] Running time: 0.000038
I1225 21:58:26.477847 140102087153472 auto_var.py:261] Running time: 0.000039


ValueError: not enough values to unpack (expected 2, got 0)

In [9]:
def get_arch(path):
    return path.split("-")[path.split("-").index('tor')+1]

def get_ds(path):
    return path.split("-")[1]

def predict_real(model, X):
    X = X.transpose(0, 3, 1, 2)
    dataset = data_utils.TensorDataset(torch.from_numpy(X).float())
    loader = torch.utils.data.DataLoader(dataset, batch_size=128, shuffle=False, num_workers=2)
    ret = []
    for [x] in loader:
        ret.append(model(x.to('cuda')).detach().cpu().numpy())
    return np.concatenate(ret, axis=0)

def calc_lip(model, X, Xp, top_norm, btm_norm):
    top = np.linalg.norm(predict_real(model, X)-predict_real(model, Xp), ord=top_norm, axis=1)
    down = np.linalg.norm(X.reshape(len(Xp), -1)-Xp.reshape(len(Xp), -1), ord=btm_norm, axis=1)
    return top / (down+1e-6)

def get_lip(model, X, top_norm=2, btm_norm=2, epsilon=1.0):
    lip = estimate_local_lip_v2(model, X, top_norm=top_norm, btm_norm=btm_norm, epsilon=epsilon)
    lip_ = calc_lip(model, X, lip, top_norm=top_norm, btm_norm=btm_norm)
    return lip_

class ModelWrapper():
    def __init__(self, model):
        self.model = model
    def predict_real(self, X):
        return predict_real(self.model, X)
    def predict(self, X):
        return predict_real(self.model, X).argmax(axis=1)

In [10]:
model_path = "./models/pgd-mnist-0.031-ce-tor-CNN001-inf-0.pt"
model = globals()[get_arch(model_path)](n_classes=10)
model.load_state_dict(torch.load(model_path))
model.eval()
model.cuda()

trnX, trny, tstX, tsty = auto_var.get_var_with_argument("dataset", get_ds(model_path))
lip_ = get_lip(model, trnX, btm_norm=np.inf, epsilon=0.03)
print(lip_.mean())

30.94554163004557
30.943932


In [11]:
trny

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [32]:
lip_ = get_lip(model, trnX)

0.0775341446240743


In [34]:
np.attacks.torch.projected_gradient_descent import ProjectedGradientDescent
nb_iter=10
attack_model = ProjectedGradientDescent(
    model_fn=model,
    norm=np.inf,
    eps=0.1,
    eps_iter=0.1*2/nb_iter,
    nb_iter=nb_iter,
)

adv_trnX = attack_model.perturb(trnX)
adv_tstX = attack_model.perturb(tstX)
print((ModelWrapper(model).predict(trnX) == trny).mean())
print((ModelWrapper(model).predict(adv_trnX) == trny).mean())

0.07753084

In [17]:
ModelWrapper(model).predict(trnX)

array([5, 0, 4, ..., 5, 6, 8])

In [22]:
model(torch.Tensor(trnX[0:10].transpose(0, 3, 1, 2)))

tensor([[  1.1423, -15.6917,  -2.8912,  10.5858, -23.0581,  16.7434, -13.0156,
          -4.2783,  -6.4978,  -4.8898],
        [ 37.1476, -22.2011,  -6.6458,  -2.7661, -23.4233,  11.0323, -16.3949,
           0.3449,  -4.4311,  -9.6248],
        [ -9.1166,  -7.7489,  -7.2385,  -2.2442,  18.8515,  -1.9383,  -7.7448,
          -0.3562,  -2.3477,   9.9469],
        [-11.4429,  15.3514,  -1.6532,  -1.5187,  -1.6904,  -6.5238,  -9.2465,
           1.9417,   2.3212,  -1.5107],
        [-11.5020,  -6.4233, -10.5065,  -9.7716,  11.6808,  -0.2899, -14.0837,
           7.9795,   0.2486,  22.2252],
        [ -5.8696, -16.1103,  20.7923,  -2.4183, -11.1075,  -6.0231,  -9.4093,
           0.1035,  -1.5336,  -0.1243],
        [-12.1381,  18.7317,   1.8925,   1.5545,  -6.0536,  -4.0237,  -6.7087,
          -4.4256,  -0.2390,  -3.4156],
        [  1.6682, -14.4947,   6.3997,  30.9872, -23.0401,   4.2524, -27.6506,
         -12.2829,   5.5641,   0.2893],
        [-10.8424,  15.2722,  -2.2534,  -2.2202,