In [1]:
import re

import joblib
import numpy as np
import torch
import torch.utils.data as data_utils

from lolip.models.torch_utils.archs import *
from lolip.variables import auto_var
from lolip.utils import estimate_local_lip, estimate_local_lip_v2
from params import mnistLip, cifarLip
from utils import params_to_dataframe

In [2]:
_, _, grid_params, _ = mnistLip()()
params_to_dataframe(grid_params, columns=['trn_acc', 'tst_acc', 'adv_trn_acc', 'adv_tst_acc', 'avg_trn_lip', 'avg_tst_lip', 'history'], result_file_dir='./results/experiment01/')

I1227 21:08:00.769924 140466971535168 auto_var.py:261] Running time: 0.002669
I1227 21:08:00.839650 140466971535168 auto_var.py:261] Running time: 0.002452
I1227 21:08:00.904117 140466971535168 auto_var.py:261] Running time: 0.002363
I1227 21:08:00.969008 140466971535168 auto_var.py:261] Running time: 0.002387
E1227 21:08:01.091969 140466971535168 auto_var.py:341] Error with {'attack': 'pgd', 'dataset': 'mnist', 'eps': 0.1, 'model': 'curece-tor-CNN001', 'norm': 'inf', 'random_seed': 0}
I1227 21:08:01.095717 140466971535168 auto_var.py:261] Running time: 0.002391
I1227 21:08:01.159331 140466971535168 auto_var.py:261] Running time: 0.002353
I1227 21:08:01.223318 140466971535168 auto_var.py:261] Running time: 0.002401
I1227 21:08:01.284942 140466971535168 auto_var.py:261] Running time: 0.000113


problem with ./results/experiment01/pgd-mnist-0.1-curece-tor-CNN001-inf-0.pkl


I1227 21:08:01.349153 140466971535168 auto_var.py:261] Running time: 0.002390
I1227 21:08:01.414107 140466971535168 auto_var.py:261] Running time: 0.002356
I1227 21:08:01.478590 140466971535168 auto_var.py:261] Running time: 0.002352
I1227 21:08:01.542494 140466971535168 auto_var.py:261] Running time: 0.002425
I1227 21:08:01.606361 140466971535168 auto_var.py:261] Running time: 0.002427
I1227 21:08:01.670421 140466971535168 auto_var.py:261] Running time: 0.002383
I1227 21:08:01.734451 140466971535168 auto_var.py:261] Running time: 0.002336
I1227 21:08:01.798408 140466971535168 auto_var.py:261] Running time: 0.002336
I1227 21:08:01.860166 140466971535168 auto_var.py:261] Running time: 0.000116


attack  dataset  eps                  model norm  random_seed   trn_acc  \
0     pgd    mnist  0.1          ce-tor-CNN001  inf            0  1.000000   
1     pgd    mnist  0.1    tradesce-tor-CNN001  inf            0  1.000000   
2     pgd    mnist  0.1   trades6ce-tor-CNN001  inf            0  0.999967   
3     pgd    mnist  0.1  trades10ce-tor-CNN001  inf            0  0.999967   
4     pgd    mnist  0.1       advce-tor-CNN001  inf            0  0.999817   
5     pgd    mnist  0.1     llr65ce-tor-CNN001  inf            0  0.999400   
6     pgd    mnist  0.1       llrce-tor-CNN001  inf            0  0.999983   
7     pgd  fashion  0.1          ce-tor-CNN001  inf            0  0.999533   
8     pgd  fashion  0.1    tradesce-tor-CNN001  inf            0  0.996783   
9     pgd  fashion  0.1   trades6ce-tor-CNN001  inf            0  0.976017   
10    pgd  fashion  0.1  trades10ce-tor-CNN001  inf            0  0.963883   
11    pgd  fashion  0.1      curece-tor-CNN001  inf            0  1.000000   
12    pgd  fashion  0.1       advce-tor-CNN001  inf            0  0.888167   
13    pgd  fashion  0.1     llr65ce-tor-CNN001  inf            0  0.955950   
14    pgd  fashion  0.1       llrce-tor-CNN001  inf            0  0.975550   

    tst_acc  adv_trn_acc  adv_tst_acc  avg_trn_lip  avg_tst_lip  \
0    0.9920     0.408133       0.4183    24.914808    25.083706   
1    0.9922     0.806650       0.8088     6.701021     6.729030   
2    0.9924     0.919833       0.9062     5.737867     5.748982   
3    0.9931     0.921550       0.9043     5.052001     5.040387   
4    0.9931     0.996400       0.9670     2.771575     2.795055   
5    0.9916     0.839967       0.8302    13.091495    13.002464   
6    0.9934     0.860450       0.8399    12.434842    12.424883   
7    0.9263     0.008750       0.0558    76.034775    76.180283   
8    0.9308     0.246233       0.2813    22.103630    21.940477   
9    0.9194     0.503983       0.5260     8.076009     8.072925   
10   0.9130     0.571000       0.5846     5.593621     5.636191   
11   0.9214     0.076683       0.1263    28.173588    27.971794   
12   0.8686     0.829900       0.8119     1.136331     1.133796   
13   0.9109     0.435117       0.4444    12.036719    12.132747   
14   0.9157     0.393817       0.4215     9.833105     9.933347   

                                              history  
0   [{'epoch': 1, 'trn_loss': 0.4666699381828308, ...  
1   [{'epoch': 1, 'trn_loss': 0.46601010074218113,...  
2   [{'epoch': 1, 'trn_loss': 0.4758203192869822, ...  
3   [{'epoch': 1, 'trn_loss': 0.4963904350121816, ...  
4   [{'epoch': 1, 'trn_loss': 0.7555228825410207, ...  
5   [{'epoch': 1, 'trn_loss': 2.5009387490272523, ...  
6   [{'epoch': 1, 'trn_loss': 1.71617512169679, 't...  
7   [{'epoch': 1, 'trn_loss': 0.6656579953034719, ...  
8   [{'epoch': 1, 'trn_loss': 0.703578668832779, '...  
9   [{'epoch': 1, 'trn_loss': 0.7347536305745442, ...  
10  [{'epoch': 1, 'trn_loss': 0.7621811085700989, ...  
11  [{'epoch': 1, 'trn_loss': 0.6511157069206238, ...  
12  [{'epoch': 1, 'trn_loss': 1.1296655715942383, ...  
13  [{'epoch': 1, 'trn_loss': 5.315398379262288, '...  
14  [{'epoch': 1, 'trn_loss': 3.6845599964141846, ...

In [6]:
a = joblib.load("./results/experiment01/pgd-fashion-0.1-advce-tor-CNN001-inf-0.pkl")

[{'epoch': 1,
  'trn_loss': 1.1296655715942383,
  'trn_acc': 0.5623166666666667,
  'tst_loss': 0.5974252161979675,
  'tst_acc': 0.7711},
 {'epoch': 2,
  'trn_loss': 0.8699527779897054,
  'trn_acc': 0.6542,
  'tst_loss': 0.5402977557182312,
  'tst_acc': 0.7974},
 {'epoch': 3,
  'trn_loss': 0.8079269249598185,
  'trn_acc': 0.6762166666666667,
  'tst_loss': 0.51998665599823,
  'tst_acc': 0.7931},
 {'epoch': 4,
  'trn_loss': 0.7753438138961792,
  'trn_acc': 0.6892166666666667,
  'tst_loss': 0.49689228239059446,
  'tst_acc': 0.8134},
 {'epoch': 5,
  'trn_loss': 0.7505436100006103,
  'trn_acc': 0.6993666666666667,
  'tst_loss': 0.4920894338607788,
  'tst_acc': 0.8211},
 {'epoch': 6,
  'trn_loss': 0.7304128476142884,
  'trn_acc': 0.7077833333333333,
  'tst_loss': 0.48443895540237425,
  'tst_acc': 0.8124},
 {'epoch': 7,
  'trn_loss': 0.7132356996536255,
  'trn_acc': 0.71615,
  'tst_loss': 0.47015627117156983,
  'tst_acc': 0.8219},
 {'epoch': 8,
  'trn_loss': 0.6972585690180461,
  'trn_acc': 0.

In [3]:
_, _, grid_params, _ = cifarLip()()
print(grid_params)
params_to_dataframe(grid_params, columns=['trn_acc', 'history'], result_file_dir='./results/experiment01/')

I1227 13:48:12.324988 140701727942464 auto_var.py:261] Running time: 0.000077
I1227 13:48:12.397220 140701727942464 auto_var.py:261] Running time: 0.000088
I1227 13:48:12.458136 140701727942464 auto_var.py:261] Running time: 0.000111
I1227 13:48:12.518842 140701727942464 auto_var.py:261] Running time: 0.000042


[{'dataset': ['cifar10'], 'model': ['ce-tor-WRN_40_10', 'trades6ce-tor-WRN_40_10', 'curece-tor-WRN_40_10', 'advce-tor-WRN_40_10', 'llrce-tor-WRN_40_10'], 'eps': [0.031], 'norm': ['inf'], 'attack': ['pgd'], 'random_seed': [0]}]


I1227 13:48:12.578666 140701727942464 auto_var.py:261] Running time: 0.000042


ValueError: not enough values to unpack (expected 2, got 0)

In [9]:
def get_arch(path):
    return path.split("-")[path.split("-").index('tor')+1]

def get_ds(path):
    return path.split("-")[1]

def predict_real(model, X):
    X = X.transpose(0, 3, 1, 2)
    dataset = data_utils.TensorDataset(torch.from_numpy(X).float())
    loader = torch.utils.data.DataLoader(dataset, batch_size=128, shuffle=False, num_workers=2)
    ret = []
    for [x] in loader:
        ret.append(model(x.to('cuda')).detach().cpu().numpy())
    return np.concatenate(ret, axis=0)

def calc_lip(model, X, Xp, top_norm, btm_norm):
    top = np.linalg.norm(predict_real(model, X)-predict_real(model, Xp), ord=top_norm, axis=1)
    down = np.linalg.norm(X.reshape(len(Xp), -1)-Xp.reshape(len(Xp), -1), ord=btm_norm, axis=1)
    return top / (down+1e-6)

def get_lip(model, X, top_norm=2, btm_norm=2, epsilon=1.0):
    lip = estimate_local_lip_v2(model, X, top_norm=top_norm, btm_norm=btm_norm, epsilon=epsilon)
    lip_ = calc_lip(model, X, lip, top_norm=top_norm, btm_norm=btm_norm)
    return lip_

class ModelWrapper():
    def __init__(self, model):
        self.model = model
    def predict_real(self, X):
        return predict_real(self.model, X)
    def predict(self, X):
        return predict_real(self.model, X).argmax(axis=1)

In [10]:
model_path = "./models/pgd-mnist-0.031-ce-tor-CNN001-inf-0.pt"
model = globals()[get_arch(model_path)](n_classes=10)
model.load_state_dict(torch.load(model_path))
model.eval()
model.cuda()

trnX, trny, tstX, tsty = auto_var.get_var_with_argument("dataset", get_ds(model_path))
lip_ = get_lip(model, trnX, btm_norm=np.inf, epsilon=0.03)
print(lip_.mean())

30.94554163004557
30.943932


In [11]:
trny

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [32]:
lip_ = get_lip(model, trnX)

0.0775341446240743


In [34]:
np.attacks.torch.projected_gradient_descent import ProjectedGradientDescent
nb_iter=10
attack_model = ProjectedGradientDescent(
    model_fn=model,
    norm=np.inf,
    eps=0.1,
    eps_iter=0.1*2/nb_iter,
    nb_iter=nb_iter,
)

adv_trnX = attack_model.perturb(trnX)
adv_tstX = attack_model.perturb(tstX)
print((ModelWrapper(model).predict(trnX) == trny).mean())
print((ModelWrapper(model).predict(adv_trnX) == trny).mean())

0.07753084

In [17]:
ModelWrapper(model).predict(trnX)

array([5, 0, 4, ..., 5, 6, 8])

In [22]:
model(torch.Tensor(trnX[0:10].transpose(0, 3, 1, 2)))

tensor([[  1.1423, -15.6917,  -2.8912,  10.5858, -23.0581,  16.7434, -13.0156,
          -4.2783,  -6.4978,  -4.8898],
        [ 37.1476, -22.2011,  -6.6458,  -2.7661, -23.4233,  11.0323, -16.3949,
           0.3449,  -4.4311,  -9.6248],
        [ -9.1166,  -7.7489,  -7.2385,  -2.2442,  18.8515,  -1.9383,  -7.7448,
          -0.3562,  -2.3477,   9.9469],
        [-11.4429,  15.3514,  -1.6532,  -1.5187,  -1.6904,  -6.5238,  -9.2465,
           1.9417,   2.3212,  -1.5107],
        [-11.5020,  -6.4233, -10.5065,  -9.7716,  11.6808,  -0.2899, -14.0837,
           7.9795,   0.2486,  22.2252],
        [ -5.8696, -16.1103,  20.7923,  -2.4183, -11.1075,  -6.0231,  -9.4093,
           0.1035,  -1.5336,  -0.1243],
        [-12.1381,  18.7317,   1.8925,   1.5545,  -6.0536,  -4.0237,  -6.7087,
          -4.4256,  -0.2390,  -3.4156],
        [  1.6682, -14.4947,   6.3997,  30.9872, -23.0401,   4.2524, -27.6506,
         -12.2829,   5.5641,   0.2893],
        [-10.8424,  15.2722,  -2.2534,  -2.2202,